spring.application.name=URL-Shortner
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=@Vaibhavkumar9120

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=ThisIsAVeryLongSecretKeyForMyUrlShortenerApplication2026SecureKey
jwt.expiration=86400000